### ISSUE TITLE
Uncompressed binary

### ISSUE THREAD

**Issue by johnuopini** [taiki-e/upload-rust-binary-action#14] opened 2022-03-28 13:54 UTC
I see that there is no way to avoid compression since setting tar and zip both to none will generate an error. Would be nice to have a way to skip compression and upload an uncompressed binary as it makes it easier to use in a shell script.

**Comment by taiki-e** [comment] 2022-03-28 16:57
Duplicate of https://github.com/taiki-e/upload-rust-binary-action/issues/6

**Closed by taiki-e** 2022-03-28 16:57 UTC
