### ISSUE TITLE
Question: skip `tag` check?

### ISSUE THREAD

**Issue by linrongbin16** [taiki-e/upload-rust-binary-action#71] opened 2024-04-08 23:12 UTC
I want to build nightly executables, so the action is not running on a `tag`.

How to skip the `tag` check?

**Comment by taiki-e** [comment] 2024-04-09 03:12
I believe this is a duplicate of https://github.com/taiki-e/upload-rust-binary-action/issues/34.

> Since GitHub releases are associated with tags, to know which release to upload binaries to, we need information about the tag.
> 
> It refers to GITHUB_REF by default, but you can specify this using the [`ref` input option](https://github.com/taiki-e/upload-rust-binary-action/blob/0b10335ed20430900b5597e792b8f95be95e8aa2/action.yml#L58-L63). Therefore, you can upload binaries from any event by specifying the `ref` input option.

See also https://github.com/taiki-e/upload-rust-binary-action#supported-events.

**Closed by taiki-e** 2024-04-09 03:12 UTC

**Comment by linrongbin16** [comment] 2024-04-09 03:31
thank you!
